"""Teach-commented starter code for bare_metal_app projects.

Working blink + UART hello-world, with a comment on every non-obvious line explaining *what*
and *why*. Honesty rule: register addresses are **family-reference constants** cited in the file
header (curated, like the board seeds — not invented per board); board-specific runtime values
(clock, flash/RAM) come from the verified facts in SQLite. Unknown families get a teach skeleton
with explicit `TODO: from your datasheet` placeholders — never a guess.
"""
from __future__ import annotations

from typing import Any

# Reset clock (HSI) per family — a cited family constant, used for the UART baud divisor.
_HSI_HZ = {"stm32f1": 8_000_000, "stm32f4": 16_000_000}


def family_of(soc_name: str | None, arch: str | None) -> str:
    s = (soc_name or "").upper()
    if s.startswith("STM32F1"):
        return "stm32f1"
    if s.startswith("STM32F4") or s.startswith("STM32F7") or s.startswith("STM32H7"):
        return "stm32f4"   # close-enough register model for a teaching blink/UART
    if s == "RP2040":
        return "rp2040"
    return "generic"


def _brr(hsi_hz: int, baud: int = 115200) -> str:
    return f"0x{round(hsi_hz / baud):X}"


def _max_clock_note(facts: dict) -> str:
    v = facts.get("sysclk_max_hz")
    if v:
        try:
            return (f"   This chip can reach {int(v) // 1_000_000} MHz once you configure the "
                    f"PLL (a later project); we run at the reset clock here.\n")
        except (TypeError, ValueError):
            pass
    return ""


def _stm32f1(data: dict) -> str:
    hsi = _HSI_HZ["stm32f1"]
    brr = _brr(hsi)
    note = _max_clock_note(data.get("facts", {}))
    return f"""/*
 * Auto-generated by EAEDK — bare-metal blink + UART for {data['board_name']}.
 * Register addresses: STM32F10x Reference Manual (RM0008). Runtime clock: reset HSI {hsi // 1_000_000} MHz.
{note} *
 * Build:  cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake && cmake --build build
 */
#include <stdint.h>

/* Peripheral registers (RM0008). Peripherals are OFF at reset to save power — you must
 * enable each one's clock in RCC before touching it. */
#define RCC_APB2ENR (*(volatile uint32_t *)0x40021018u)  /* enables GPIO ports + USART1 */
#define GPIOC_CRH   (*(volatile uint32_t *)0x40011004u)  /* config for pins 8..15 (LED = PC13) */
#define GPIOC_ODR   (*(volatile uint32_t *)0x4001100Cu)  /* output data register (drive the pin) */
#define GPIOA_CRH   (*(volatile uint32_t *)0x40010804u)  /* config for pins 8..15 (USART1 TX = PA9) */
#define USART1_SR   (*(volatile uint32_t *)0x40013800u)
#define USART1_DR   (*(volatile uint32_t *)0x40013804u)
#define USART1_BRR  (*(volatile uint32_t *)0x40013808u)
#define USART1_CR1  (*(volatile uint32_t *)0x4001380Cu)

static void clocks_init(void)
{{
    /* Turn on the clocks for GPIOA, GPIOC and USART1. Bit positions are from RM0008. */
    RCC_APB2ENR |= (1u << 2)    /* IOPAEN  — GPIOA (USART1 TX pin)               */
                 | (1u << 4)    /* IOPCEN  — GPIOC (the on-board LED on PC13)    */
                 | (1u << 14)   /* USART1EN — the serial peripheral              */
                 | (1u << 0);   /* AFIOEN  — alternate-function mux for PA9      */
}}

static void led_init(void)
{{
    /* PC13: the Blue Pill's user LED. Configure as a push-pull output, 2 MHz.
     * Each pin uses 4 bits in CRH; PC13 is bits [23:20] -> 0b0010 = output 2MHz, push-pull. */
    GPIOC_CRH &= ~(0xFu << 20);
    GPIOC_CRH |=  (0x2u << 20);
}}

static void uart_init(void)
{{
    /* PA9 = USART1 TX. Alternate-function push-pull, 50 MHz -> CRH bits [7:4] = 0b1011. */
    GPIOA_CRH &= ~(0xFu << 4);
    GPIOA_CRH |=  (0xBu << 4);
    USART1_BRR = {brr}u;            /* baud = clock/baud = {hsi}/115200 -> 115200 8N1 */
    USART1_CR1 = (1u << 13)         /* UE — enable the UART                           */
               | (1u << 3);         /* TE — enable the transmitter                    */
}}

static void uart_putc(char c)
{{
    while (!(USART1_SR & (1u << 7))) {{ }}  /* wait until TXE: the transmit buffer is empty */
    USART1_DR = (uint8_t)c;                 /* writing DR sends the byte                    */
}}

static void uart_puts(const char *s) {{ while (*s) uart_putc(*s++); }}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    uart_puts("Hello from {data['board_name']} — EAEDK\\r\\n");

    for (;;) {{
        GPIOC_ODR ^= (1u << 13);            /* toggle PC13: flip the LED on/off */
        for (volatile uint32_t i = 0; i < 200000u; i++) {{ }}  /* crude delay (no timer yet) */
    }}
}}
"""


def _stm32f4(data: dict) -> str:
    hsi = _HSI_HZ["stm32f4"]
    brr = _brr(hsi)
    note = _max_clock_note(data.get("facts", {}))
    return f"""/*
 * Auto-generated by EAEDK — bare-metal blink + UART for {data['board_name']}.
 * Register addresses: STM32F4 Reference Manual (RM0383/RM0090). Runtime clock: reset HSI {hsi // 1_000_000} MHz.
{note} *
 * Build:  cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake && cmake --build build
 */
#include <stdint.h>

/* Registers (RM0383). On STM32F4, GPIO is on the AHB1 bus and USART2 on APB1. */
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830u)  /* enables GPIO ports */
#define RCC_APB1ENR (*(volatile uint32_t *)0x40023840u)  /* enables USART2     */
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000u)  /* pin mode (in/out/AF) */
#define GPIOA_AFRL  (*(volatile uint32_t *)0x40020020u)  /* alternate-function select, pins 0..7 */
#define GPIOA_ODR   (*(volatile uint32_t *)0x40020014u)
#define USART2_SR   (*(volatile uint32_t *)0x40004400u)
#define USART2_DR   (*(volatile uint32_t *)0x40004404u)
#define USART2_BRR  (*(volatile uint32_t *)0x40004408u)
#define USART2_CR1  (*(volatile uint32_t *)0x4000440Cu)

static void clocks_init(void)
{{
    RCC_AHB1ENR |= (1u << 0);   /* GPIOAEN — GPIOA holds the LED (PA5) and USART2 TX (PA2) */
    RCC_APB1ENR |= (1u << 17);  /* USART2EN — the VCP serial port wired to the ST-Link     */
}}

static void led_init(void)
{{
    /* PA5 = Nucleo green LED (LD2). MODER uses 2 bits per pin; pin5 -> bits [11:10] = 0b01 (output). */
    GPIOA_MODER &= ~(0x3u << 10);
    GPIOA_MODER |=  (0x1u << 10);
}}

static void uart_init(void)
{{
    /* PA2 = USART2 TX. Set MODER to alternate-function (0b10) and AFRL to AF7 (USART2). */
    GPIOA_MODER &= ~(0x3u << 4);
    GPIOA_MODER |=  (0x2u << 4);
    GPIOA_AFRL  &= ~(0xFu << 8);
    GPIOA_AFRL  |=  (0x7u << 8);
    USART2_BRR = {brr}u;            /* baud = {hsi}/115200 -> 115200 8N1 */
    USART2_CR1 = (1u << 13) | (1u << 3);  /* UE | TE */
}}

static void uart_putc(char c)
{{
    while (!(USART2_SR & (1u << 7))) {{ }}  /* wait for TXE (transmit buffer empty) */
    USART2_DR = (uint8_t)c;
}}

static void uart_puts(const char *s) {{ while (*s) uart_putc(*s++); }}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    uart_puts("Hello from {data['board_name']} — EAEDK\\r\\n");

    for (;;) {{
        GPIOA_ODR ^= (1u << 5);             /* toggle PA5: blink the LED */
        for (volatile uint32_t i = 0; i < 800000u; i++) {{ }}
    }}
}}
"""


def _skeleton(data: dict) -> str:
    arch = data["soc"]["arch"] if data["soc"] else "unknown"
    return f"""/*
 * Auto-generated by EAEDK — teach skeleton for {data['board_name']} ({arch}).
 * EAEDK doesn't have a register-level template for this family yet, so this is a structure to
 * fill in — it will NOT blink/print until you add your MCU's register init. Get the addresses
 * from your datasheet's register map (or run `eaedk ingest` on the datasheet), never guess.
 */
#include <stdint.h>

static void clocks_init(void)
{{
    /* TODO: enable the clock for the GPIO port and UART you'll use.
     *       Peripherals are off at reset to save power. (Datasheet: RCC / clock control.) */
}}

static void led_init(void)
{{
    /* TODO: configure your LED's GPIO pin as an output. (Schematic: which pin is the LED?) */
}}

static void uart_init(void)
{{
    /* TODO: configure the UART TX pin + baud rate. (Datasheet: USART registers; your clock.) */
}}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    for (;;) {{
        /* TODO: toggle the LED, print over UART. Start with blink (the simplest win). */
    }}
}}
"""


def render_main_c(data: dict) -> str:
    fam = family_of(data["soc"]["name"] if data["soc"] else None,
                    data["soc"]["arch"] if data["soc"] else None)
    return {"stm32f1": _stm32f1, "stm32f4": _stm32f4}.get(fam, _skeleton)(data)


# --- AVR (Arduino) blink + UART (v1.9.2) -----------------------------------
# Uses standard <avr/io.h> register names (avr-libc) — these are the documented ATmega names,
# not invented addresses, so the truth hierarchy holds. F_CPU 16 MHz is the Uno/Mega crystal.

_AVR_LED = {"ATMEGA328P": ("B", 5, "Uno's pin 13 (PB5)"),
            "ATMEGA2560": ("B", 7, "Mega's pin 13 (PB7)")}
_AVR_BAUD = 9600          # the Arduino Serial Monitor default — rock-solid at 16 MHz


def render_avr_main_c(data: dict) -> str:
    soc = (data["soc"]["name"] if data["soc"] else "").upper()
    port, bit, where = _AVR_LED.get(soc, ("B", 5, "your LED pin (check the board pinout)"))
    ubrr = round(16_000_000 / (16 * _AVR_BAUD)) - 1
    board = data["board_name"]
    return f"""/*
 * Auto-generated by EAEDK — bare-metal blink + UART for {board}.
 * Register names are standard avr-libc (<avr/io.h>) for the {soc or 'ATmega'} — see the device
 * datasheet. Runtime clock: 16 MHz crystal (the Arduino board's oscillator).
 *
 * Build & flash:  see START_HERE.md  (avr-gcc -> avr-objcopy -> avrdude)
 */
#include <avr/io.h>
#define F_CPU 16000000UL        /* 16 MHz — the crystal on the Arduino board */
#include <util/delay.h>

#define LED_BIT {bit}                 /* the on-board LED: {where} */

static void led_init(void)
{{
    /* Make the LED pin an OUTPUT. DDR{port} = Data Direction Register for port {port};
     * a 1 bit = output. */
    DDR{port} |= (1 << LED_BIT);
}}

static void uart_init(void)
{{
    /* USART0 at {_AVR_BAUD} baud, 8N1. UBRR0 sets the baud divisor for the 16 MHz clock. */
    UBRR0H = (unsigned char)({ubrr} >> 8);
    UBRR0L = (unsigned char)({ubrr});
    UCSR0B = (1 << TXEN0);                       /* enable the transmitter */
    UCSR0C = (1 << UCSZ01) | (1 << UCSZ00);      /* 8 data bits, no parity, 1 stop bit */
}}

static void uart_putc(char c)
{{
    while (!(UCSR0A & (1 << UDRE0))) {{ }}        /* wait until the data register is empty */
    UDR0 = c;                                    /* writing UDR0 sends the byte */
}}

static void uart_puts(const char *s) {{ while (*s) uart_putc(*s++); }}

int main(void)
{{
    led_init();
    uart_init();
    uart_puts("Hello from {board} — EAEDK\\r\\n");

    for (;;) {{
        PORT{port} ^= (1 << LED_BIT);             /* flip the LED on/off */
        _delay_ms(500);                          /* wait half a second */
    }}
}}
"""


def render_avr_start_here(data: dict) -> str:
    """Plain-language on-ramp for an AVR/Arduino board — the avr-gcc + avrdude flow, no CMake."""
    from .install import normalize_os
    soc = (data["soc"]["name"] if data["soc"] else "atmega328p").lower()
    mcu = soc if soc.startswith("atmega") else "atmega328p"
    name = data["board_name"]
    host = normalize_os(data.get("host_os", ""))
    if host == "linux":
        install = "On **Ubuntu/Debian**:\n```bash\nsudo apt install gcc-avr avr-libc avrdude\n```"
    elif host == "macos":
        install = "On **macOS (Homebrew)**:\n```bash\nbrew install avr-gcc avrdude\n```"
    elif host == "windows":
        install = ("On **Windows**: install the AVR toolchain + avrdude (e.g. via WinAVR or "
                   "MSYS2 `pacman -S mingw-w64-x86_64-avr-gcc`), and avrdude from "
                   "https://github.com/avrdudes/avrdude/releases.")
    else:
        install = ("Install `avr-gcc`, `avr-libc`, and `avrdude` for your OS (they come with the "
                   "Arduino IDE too).")
    return f"""# START HERE — {name}

You asked EAEDK for a starting point. Here's what's in this folder and what to do, in order.

## What these files are
- **`src/main.c`** — your program: a **working** blink + UART for {name}. Every non-obvious line
  has a comment. The on-board LED blinks and it prints "Hello" over serial.
- **`FLASH.md`** — extra notes on getting the program onto the board.
- **`BRINGUP_CHECKLIST.md`** — everything EAEDK checked, and what's still missing.

## Install the tools first
You need an AVR compiler and the `avrdude` flasher.

{install}

## Build it
```bash
avr-gcc -mmcu={mcu} -DF_CPU=16000000UL -Os -o blink.elf src/main.c
avr-objcopy -O ihex blink.elf blink.hex
```

## Flash it
Plug the board in over USB, then (the port is often `/dev/ttyACM0` on Linux, `/dev/cu.usbmodemXXXX`
on macOS, or `COM3` on Windows — check which one appears when you plug it in):
```bash
avrdude -c arduino -p {mcu} -P /dev/ttyACM0 -b 115200 -U flash:w:blink.hex
```

## Then
Open a serial terminal at **{_AVR_BAUD} 8N1** to see the "Hello" message, and watch the on-board
LED blink. That's the whole build → flash → run loop working.

Run `eaedk mentor --board "{name}"` any time to see your full learning path and the *why* behind
each step.
"""


# --- v1.9.0 F3: goal-aware review artifact ---------------------------------

def render_dtb_node(data: dict) -> str:
    """Device-tree node skeleton for a Linux/driver bring-up. Cites a register base from a
    verified fact when present; otherwise explicit <TODO ...> placeholders — never a guess."""
    name = data["board_name"]
    soc = data["soc"]["name"] if data["soc"] else "your SoC"
    facts = data.get("facts", {})
    # Use a verified i2c/peripheral base only if it's in the cited facts; else placeholder.
    base = None
    for k, v in facts.items():
        if "i2c" in k.lower() and ("base" in k.lower() or "addr" in k.lower()):
            base = v
            break
    soc_node = f"0x{base:08X}" if isinstance(base, int) else "<TODO peripheral base from RM>"
    return f"""/*
 * Device Tree node skeleton for {name} ({soc}).
 * EAEDK never guesses an address — fill every <TODO ...> from the SoC reference manual / the
 * vendor .dtsi. This adds a missing I2C peripheral's child node (the most common DTB gap).
 */
&i2c1 {{                                  /* the controller node (label from your SoC .dtsi) */
    status = "okay";
    clock-frequency = <100000>;          /* 100 kHz standard mode; 400000 for fast mode */
    pinctrl-names = "default";

    sensor@<TODO 7-bit addr> {{           /* e.g. sensor@68 */
        compatible = "<TODO vendor,part>";          /* MUST match the driver's of_match_table */
        reg = <0x<TODO 7-bit I2C address>>;         /* the device's bus address, not a memory base */
        interrupt-parent = <&<TODO gpio/intc label>>;   /* required if the device has an IRQ line */
        interrupts = <<TODO line> <TODO flags>>;
    }};
}};

/* Controller register base (for cross-checking the node label against the SoC map):
 *   {soc} i2c1 @ {soc_node}
 * After editing: recompile the DTB, reboot, and re-run `eaedk log analyze --deep` on dmesg.
 */
"""


def render_partition_review(data: dict) -> str:
    """A readable map of the project's OTA partitions for the Critic to inspect. Overlap/fit are
    confirmed deterministically by the grounded validation pass, not by this text."""
    parts = (data.get("inputs") or {}).get("partitions")
    name = data["board_name"]
    L = [f"/* OTA partition table review — {name} */"]
    if not isinstance(parts, list) or not parts:
        L.append("/* No 'partitions' input provided. Set it with: eaedk input set <project> "
                 "partitions '[{name,role,base,size}, ...]' so EAEDK can check overlap/fit. */")
        return "\n".join(L) + "\n"
    L.append("# role        base          size          end")
    for p in parts:
        try:
            base, size = int(p.get("base")), int(p.get("size"))
            L.append(f"# {str(p.get('role') or p.get('name')):<10} "
                     f"0x{base:08X}    0x{size:08X}    0x{base + size:08X}")
        except (TypeError, ValueError):
            L.append(f"# {p}  (unparseable base/size)")
    L.append("# Check: A/B slots must not overlap and must fit primary storage. "
             "Run `eaedk validate <project>` for the deterministic verdict.")
    return "\n".join(L) + "\n"


# goal_type -> (artifact_kind, generator). Unlisted goals fall back to the bare-metal scaffold.
_ARTIFACT_BY_GOAL = {
    "linux": ("devicetree", render_dtb_node),
    "driver": ("devicetree", render_dtb_node),
    "ota": ("partition_table", render_partition_review),
}


def render_review_artifact(data: dict) -> tuple[str, str]:
    """F3: pick the artifact appropriate to the project's goal_type. Returns (kind, content).
    Bare-metal/bootloader keep the existing C scaffold byte-for-byte."""
    goal = data["project"]["goal_type"] if data.get("project") else "bare_metal_app"
    kind, gen = _ARTIFACT_BY_GOAL.get(goal, ("bare_metal_c", render_main_c))
    return kind, gen(data)


def render_start_here(data: dict) -> str:
    """Plain-language on-ramp for someone who has never seen a CMakeLists."""
    name = data["board_name"]
    path = data.get("learning_path", [])
    next_titles = " → ".join(s["title"] for s in path[:3]) if path else "Blink → UART → a sensor"
    fam = family_of(data["soc"]["name"] if data["soc"] else None, None)
    working = fam in ("stm32f1", "stm32f4")
    main_note = ("`src/main.c` is a **working** blink + UART program — every non-obvious line has "
                 "a comment explaining it." if working else
                 "`src/main.c` is a **skeleton** with TODOs — fill in your MCU's register init "
                 "(see the comments).")
    # Fix 1 (v1.7.0): tell the beginner exactly how to install the tools, for THEIR OS — never
    # just "a tool is missing". The install block is emitted from the board's required tools.
    from .install import install_block
    install_lines = install_block(data.get("host_os", ""), data.get("required_tools", []))
    install_md = ("\n## Install the tools first\n"
                  "You need these installed before the build below will work.\n\n"
                  + "\n".join(install_lines) + "\n") if install_lines else ""
    return f"""# START HERE — {name}

You asked EAEDK for a starting point. Here's what's in this folder and what to do, in order.

## What these files are
- **`src/main.c`** — your program. {main_note}
- **`linker/memory.ld`** — tells the compiler where your code (flash) and data (RAM) live on
  this exact chip. EAEDK filled it in from {name}'s verified memory map.
- **`cmake/toolchain.cmake`** — tells CMake to use the *cross-compiler* for this chip
  (`arm-none-eabi-gcc`), not your PC's compiler.
- **`CMakeLists.txt`** — the build recipe. You rarely edit this to start.
- **`FLASH.md`** — how to copy the built program onto the board.
- **`BRINGUP_CHECKLIST.md`** — everything EAEDK checked, and what's still missing.
{install_md}
## Build it
```bash
cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
cmake --build build
```
If that fails, run `eaedk toolchain validate` — it tells you in plain language what tool is
missing and how to install it.

## What to change first
1. Confirm the **LED pin** in `src/main.c` matches your board's schematic (it's commented).
2. Build, flash (see `FLASH.md`), and watch the LED. That's the whole loop working.
3. Open a serial terminal at **115200 8N1** to see the "Hello" message.

## What to try next
Your learning path: **{next_titles}**.
Run `eaedk mentor --board "{name}"` any time to see the full path and the *why* behind each step.
"""
