"""Teach-commented starter code for bare_metal_app projects.

Working blink + UART hello-world, with a comment on every non-obvious line explaining *what*
and *why*. Honesty rule: register addresses are **family-reference constants** cited in the file
header (curated, like the board seeds — not invented per board); board-specific runtime values
(clock, flash/RAM) come from the verified facts in SQLite. Unknown families get a teach skeleton
with explicit `TODO: from your datasheet` placeholders — never a guess.
"""
from __future__ import annotations

from typing import Any

# Reset clock (HSI) per family — a cited family constant, used for the UART baud divisor.
_HSI_HZ = {"stm32f1": 8_000_000, "stm32f4": 16_000_000}


def family_of(soc_name: str | None, arch: str | None) -> str:
    s = (soc_name or "").upper()
    if s.startswith("STM32F1"):
        return "stm32f1"
    if s.startswith("STM32F4") or s.startswith("STM32F7") or s.startswith("STM32H7"):
        return "stm32f4"   # close-enough register model for a teaching blink/UART
    if s == "RP2040":
        return "rp2040"
    return "generic"


def _brr(hsi_hz: int, baud: int = 115200) -> str:
    return f"0x{round(hsi_hz / baud):X}"


def _max_clock_note(facts: dict) -> str:
    v = facts.get("sysclk_max_hz")
    if v:
        try:
            return (f"   This chip can reach {int(v) // 1_000_000} MHz once you configure the "
                    f"PLL (a later project); we run at the reset clock here.\n")
        except (TypeError, ValueError):
            pass
    return ""


def _stm32f1(data: dict) -> str:
    hsi = _HSI_HZ["stm32f1"]
    brr = _brr(hsi)
    note = _max_clock_note(data.get("facts", {}))
    return f"""/*
 * Auto-generated by EAEDK — bare-metal blink + UART for {data['board_name']}.
 * Register addresses: STM32F10x Reference Manual (RM0008). Runtime clock: reset HSI {hsi // 1_000_000} MHz.
{note} *
 * Build:  cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake && cmake --build build
 */
#include <stdint.h>

/* Peripheral registers (RM0008). Peripherals are OFF at reset to save power — you must
 * enable each one's clock in RCC before touching it. */
#define RCC_APB2ENR (*(volatile uint32_t *)0x40021018u)  /* enables GPIO ports + USART1 */
#define GPIOC_CRH   (*(volatile uint32_t *)0x40011004u)  /* config for pins 8..15 (LED = PC13) */
#define GPIOC_ODR   (*(volatile uint32_t *)0x4001100Cu)  /* output data register (drive the pin) */
#define GPIOA_CRH   (*(volatile uint32_t *)0x40010804u)  /* config for pins 8..15 (USART1 TX = PA9) */
#define USART1_SR   (*(volatile uint32_t *)0x40013800u)
#define USART1_DR   (*(volatile uint32_t *)0x40013804u)
#define USART1_BRR  (*(volatile uint32_t *)0x40013808u)
#define USART1_CR1  (*(volatile uint32_t *)0x4001380Cu)

static void clocks_init(void)
{{
    /* Turn on the clocks for GPIOA, GPIOC and USART1. Bit positions are from RM0008. */
    RCC_APB2ENR |= (1u << 2)    /* IOPAEN  — GPIOA (USART1 TX pin)               */
                 | (1u << 4)    /* IOPCEN  — GPIOC (the on-board LED on PC13)    */
                 | (1u << 14)   /* USART1EN — the serial peripheral              */
                 | (1u << 0);   /* AFIOEN  — alternate-function mux for PA9      */
}}

static void led_init(void)
{{
    /* PC13: the Blue Pill's user LED. Configure as a push-pull output, 2 MHz.
     * Each pin uses 4 bits in CRH; PC13 is bits [23:20] -> 0b0010 = output 2MHz, push-pull. */
    GPIOC_CRH &= ~(0xFu << 20);
    GPIOC_CRH |=  (0x2u << 20);
}}

static void uart_init(void)
{{
    /* PA9 = USART1 TX. Alternate-function push-pull, 50 MHz -> CRH bits [7:4] = 0b1011. */
    GPIOA_CRH &= ~(0xFu << 4);
    GPIOA_CRH |=  (0xBu << 4);
    USART1_BRR = {brr}u;            /* baud = clock/baud = {hsi}/115200 -> 115200 8N1 */
    USART1_CR1 = (1u << 13)         /* UE — enable the UART                           */
               | (1u << 3);         /* TE — enable the transmitter                    */
}}

static void uart_putc(char c)
{{
    while (!(USART1_SR & (1u << 7))) {{ }}  /* wait until TXE: the transmit buffer is empty */
    USART1_DR = (uint8_t)c;                 /* writing DR sends the byte                    */
}}

static void uart_puts(const char *s) {{ while (*s) uart_putc(*s++); }}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    uart_puts("Hello from {data['board_name']} — EAEDK\\r\\n");

    for (;;) {{
        GPIOC_ODR ^= (1u << 13);            /* toggle PC13: flip the LED on/off */
        for (volatile uint32_t i = 0; i < 200000u; i++) {{ }}  /* crude delay (no timer yet) */
    }}
}}
"""


def _stm32f4(data: dict) -> str:
    hsi = _HSI_HZ["stm32f4"]
    brr = _brr(hsi)
    note = _max_clock_note(data.get("facts", {}))
    return f"""/*
 * Auto-generated by EAEDK — bare-metal blink + UART for {data['board_name']}.
 * Register addresses: STM32F4 Reference Manual (RM0383/RM0090). Runtime clock: reset HSI {hsi // 1_000_000} MHz.
{note} *
 * Build:  cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake && cmake --build build
 */
#include <stdint.h>

/* Registers (RM0383). On STM32F4, GPIO is on the AHB1 bus and USART2 on APB1. */
#define RCC_AHB1ENR (*(volatile uint32_t *)0x40023830u)  /* enables GPIO ports */
#define RCC_APB1ENR (*(volatile uint32_t *)0x40023840u)  /* enables USART2     */
#define GPIOA_MODER (*(volatile uint32_t *)0x40020000u)  /* pin mode (in/out/AF) */
#define GPIOA_AFRL  (*(volatile uint32_t *)0x40020020u)  /* alternate-function select, pins 0..7 */
#define GPIOA_ODR   (*(volatile uint32_t *)0x40020014u)
#define USART2_SR   (*(volatile uint32_t *)0x40004400u)
#define USART2_DR   (*(volatile uint32_t *)0x40004404u)
#define USART2_BRR  (*(volatile uint32_t *)0x40004408u)
#define USART2_CR1  (*(volatile uint32_t *)0x4000440Cu)

static void clocks_init(void)
{{
    RCC_AHB1ENR |= (1u << 0);   /* GPIOAEN — GPIOA holds the LED (PA5) and USART2 TX (PA2) */
    RCC_APB1ENR |= (1u << 17);  /* USART2EN — the VCP serial port wired to the ST-Link     */
}}

static void led_init(void)
{{
    /* PA5 = Nucleo green LED (LD2). MODER uses 2 bits per pin; pin5 -> bits [11:10] = 0b01 (output). */
    GPIOA_MODER &= ~(0x3u << 10);
    GPIOA_MODER |=  (0x1u << 10);
}}

static void uart_init(void)
{{
    /* PA2 = USART2 TX. Set MODER to alternate-function (0b10) and AFRL to AF7 (USART2). */
    GPIOA_MODER &= ~(0x3u << 4);
    GPIOA_MODER |=  (0x2u << 4);
    GPIOA_AFRL  &= ~(0xFu << 8);
    GPIOA_AFRL  |=  (0x7u << 8);
    USART2_BRR = {brr}u;            /* baud = {hsi}/115200 -> 115200 8N1 */
    USART2_CR1 = (1u << 13) | (1u << 3);  /* UE | TE */
}}

static void uart_putc(char c)
{{
    while (!(USART2_SR & (1u << 7))) {{ }}  /* wait for TXE (transmit buffer empty) */
    USART2_DR = (uint8_t)c;
}}

static void uart_puts(const char *s) {{ while (*s) uart_putc(*s++); }}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    uart_puts("Hello from {data['board_name']} — EAEDK\\r\\n");

    for (;;) {{
        GPIOA_ODR ^= (1u << 5);             /* toggle PA5: blink the LED */
        for (volatile uint32_t i = 0; i < 800000u; i++) {{ }}
    }}
}}
"""


def _skeleton(data: dict) -> str:
    arch = data["soc"]["arch"] if data["soc"] else "unknown"
    return f"""/*
 * Auto-generated by EAEDK — teach skeleton for {data['board_name']} ({arch}).
 * EAEDK doesn't have a register-level template for this family yet, so this is a structure to
 * fill in — it will NOT blink/print until you add your MCU's register init. Get the addresses
 * from your datasheet's register map (or run `eaedk ingest` on the datasheet), never guess.
 */
#include <stdint.h>

static void clocks_init(void)
{{
    /* TODO: enable the clock for the GPIO port and UART you'll use.
     *       Peripherals are off at reset to save power. (Datasheet: RCC / clock control.) */
}}

static void led_init(void)
{{
    /* TODO: configure your LED's GPIO pin as an output. (Schematic: which pin is the LED?) */
}}

static void uart_init(void)
{{
    /* TODO: configure the UART TX pin + baud rate. (Datasheet: USART registers; your clock.) */
}}

int main(void)
{{
    clocks_init();
    led_init();
    uart_init();
    for (;;) {{
        /* TODO: toggle the LED, print over UART. Start with blink (the simplest win). */
    }}
}}
"""


def render_main_c(data: dict) -> str:
    fam = family_of(data["soc"]["name"] if data["soc"] else None,
                    data["soc"]["arch"] if data["soc"] else None)
    return {"stm32f1": _stm32f1, "stm32f4": _stm32f4}.get(fam, _skeleton)(data)


def render_start_here(data: dict) -> str:
    """Plain-language on-ramp for someone who has never seen a CMakeLists."""
    name = data["board_name"]
    path = data.get("learning_path", [])
    next_titles = " → ".join(s["title"] for s in path[:3]) if path else "Blink → UART → a sensor"
    fam = family_of(data["soc"]["name"] if data["soc"] else None, None)
    working = fam in ("stm32f1", "stm32f4")
    main_note = ("`src/main.c` is a **working** blink + UART program — every non-obvious line has "
                 "a comment explaining it." if working else
                 "`src/main.c` is a **skeleton** with TODOs — fill in your MCU's register init "
                 "(see the comments).")
    return f"""# START HERE — {name}

You asked EAEDK for a starting point. Here's what's in this folder and what to do, in order.

## What these files are
- **`src/main.c`** — your program. {main_note}
- **`linker/memory.ld`** — tells the compiler where your code (flash) and data (RAM) live on
  this exact chip. EAEDK filled it in from {name}'s verified memory map.
- **`cmake/toolchain.cmake`** — tells CMake to use the *cross-compiler* for this chip
  (`arm-none-eabi-gcc`), not your PC's compiler.
- **`CMakeLists.txt`** — the build recipe. You rarely edit this to start.
- **`FLASH.md`** — how to copy the built program onto the board.
- **`BRINGUP_CHECKLIST.md`** — everything EAEDK checked, and what's still missing.

## Build it
```bash
cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake
cmake --build build
```
If that fails, run `eaedk toolchain validate` — it tells you in plain language what tool is
missing and how to install it.

## What to change first
1. Confirm the **LED pin** in `src/main.c` matches your board's schematic (it's commented).
2. Build, flash (see `FLASH.md`), and watch the LED. That's the whole loop working.
3. Open a serial terminal at **115200 8N1** to see the "Hello" message.

## What to try next
Your learning path: **{next_titles}**.
Run `eaedk mentor --board "{name}"` any time to see the full path and the *why* behind each step.
"""
