"""Pure generators for structured engineering deliverables.

Each takes an already-gathered ``data`` dict and returns file content as a string. The truth
hierarchy applies to generated artifacts too: a value we don't have is emitted as an explicit
`<UNKNOWN ...>` placeholder, never guessed. No DB, no I/O — golden-testable.
"""
from __future__ import annotations

from typing import Any

# arch -> -mcpu value for bare-metal Cortex-M.
_MCPU = {
    "arm-cortex-m0": "cortex-m0", "arm-cortex-m0plus": "cortex-m0plus",
    "arm-cortex-m3": "cortex-m3", "arm-cortex-m4": "cortex-m4",
    "arm-cortex-m7": "cortex-m7", "arm-cortex-m33": "cortex-m33",
}


def is_mcu(arch: str | None) -> bool:
    return bool(arch) and arch.startswith("arm-cortex-m")


def cpu_flag(arch: str | None) -> str | None:
    return _MCPU.get(arch or "")


def _hex(v: Any) -> str | None:
    return f"0x{v:08X}" if isinstance(v, int) else None


def _draft_banner(data: dict) -> str:
    if data["resp"].feasibility == "feasible":
        return ""
    return (f"> ⚠ DRAFT — project feasibility is {data['resp'].feasibility.upper()}. "
            "Resolve the blockers below before relying on these files.\n\n")


# --- 1) bring-up checklist -------------------------------------------------

def render_checklist(data: dict) -> str:
    resp = data["resp"]
    p = data["project"]
    L = [f"# Bring-up Checklist — {p['name']}", ""]
    L.append(_draft_banner(data).rstrip("\n"))
    L.append(f"- **Board:** {data['board_name'] or '-'}"
             + (f"  ({data['soc']['name']}, {data['soc']['arch']})" if data["soc"] else ""))
    L.append(f"- **Goal:** {p['goal_type']}")
    L.append(f"- **Template:** {resp.template or 'none'}")
    L.append(f"- **Feasibility:** {resp.feasibility.upper()}")
    L.append("")
    L.append("## Checklist")
    box = {"done": "[x]", "todo": "[ ]", "na": "[-]", "blocked": "[!]"}
    for row in data["checklist"]:
        L.append(f"- {box.get(row['status'], '[ ]')} {row['item_key']}: {row['text']}")
        if row["note"]:
            L.append(f"      - note: {row['note']}")
    if not data["checklist"]:
        L.append("- (template-less project — no checklist)")
    L.append("")
    L.append("## Validation")
    for v in resp.validations:
        L.append(f"- {v['status']}  {v['check']}: {v['reason']}")
        if v.get("teach") and v["status"] != "PASS":
            L.append(f"    - ↳ {v['teach']}")
    L.append("")
    L.append("## Facts confirmed")
    L.extend([f"- {f['key']} = {f['value']}  [{f['confidence']}]" for f in resp.facts]
             or ["- (none)"])
    L.append("")
    L.append("## Assumptions / Unknowns")
    L.extend([f"- assume: {a['key']} = {a['value']}  [{a['confidence']}]"
              for a in resp.assumptions])
    L.extend([f"- unknown: {u}" for u in resp.unknowns] or (["- (none)"] if not resp.assumptions else []))
    if data["tracked"]:
        L.append("")
        L.append("## Tracked risks (open)")
        for t in data["tracked"]:
            L.append(f"- #{t['id']} [{t['severity']}] {t['rule_key']}: "
                     f"{t['explanation'].splitlines()[0]}")
    L.append("")
    return "\n".join(L) + "\n"


# --- 2) CMake scaffold -----------------------------------------------------

def render_toolchain_cmake(data: dict) -> str:
    arch = data["soc"]["arch"] if data["soc"] else None
    cc = data["compiler_req"]["name"] if data["compiler_req"] else "<UNKNOWN cross-compiler>"
    cpu = cpu_flag(arch)
    L = ["# Auto-generated by EAEDK — cross-compilation toolchain file.", ""]
    if is_mcu(arch):
        L += ["set(CMAKE_SYSTEM_NAME Generic)",
              f"set(CMAKE_SYSTEM_PROCESSOR {arch})", ""]
        L += [f"set(CMAKE_C_COMPILER {cc})",
              f"set(CMAKE_ASM_COMPILER {cc})",
              "set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)", ""]
        flags = f"-mcpu={cpu} -mthumb" if cpu else "<UNKNOWN -mcpu: set from datasheet>"
        L += [f'set(MCU_FLAGS "{flags}")',
              'set(CMAKE_C_FLAGS "${MCU_FLAGS} -ffunction-sections -fdata-sections")',
              'set(CMAKE_EXE_LINKER_FLAGS "${MCU_FLAGS} -Wl,--gc-sections '
              '-T${CMAKE_SOURCE_DIR}/linker/memory.ld")']
    else:
        L += ["set(CMAKE_SYSTEM_NAME Linux)",
              f"set(CMAKE_SYSTEM_PROCESSOR {arch or '<UNKNOWN>'})", "",
              f"set(CMAKE_C_COMPILER {cc})",
              "# Note: this is a host/test-harness scaffold. The on-target build (U-Boot,",
              "# kernel, or vendor SDK) uses its own build system with the cross-compiler above."]
    return "\n".join(L) + "\n"


def render_cmake_lists(data: dict) -> str:
    p = data["project"]
    arch = data["soc"]["arch"] if data["soc"] else None
    name = "".join(c if c.isalnum() else "_" for c in p["name"])
    L = ["# Auto-generated by EAEDK. Configure with:",
         "#   cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain.cmake && cmake --build build",
         "cmake_minimum_required(VERSION 3.16)",
         f"project({name} C ASM)", ""]
    if is_mcu(arch):
        L += [f"add_executable(${{PROJECT_NAME}}.elf src/main.c)", "",
              "# Memory layout is in linker/memory.ld (generated from the verified board data)."]
    else:
        L += ["add_executable(${PROJECT_NAME} src/main.c)",
              "# Replace with your real sources; on-target build may use U-Boot/kernel/SDK instead."]
    return "\n".join(L) + "\n"


def render_linker(data: dict) -> str:
    """GNU ld MEMORY layout from verified board geometry (MCU only). UNKNOWN -> placeholder."""
    b = data["board"] or {}
    fb, fl = _hex(b.get("flash_base")), b.get("flash_bytes")
    rb, rl = _hex(b.get("ram_base")), b.get("ram_bytes")
    fb = fb or "<UNKNOWN flash_base>"
    rb = rb or "<UNKNOWN ram_base>"
    fl = f"{fl}" if isinstance(fl, int) else "<UNKNOWN flash_bytes>"
    rl = f"{rl}" if isinstance(rl, int) else "<UNKNOWN ram_bytes>"
    return (
        "/* Auto-generated by EAEDK from verified board data. Values marked <UNKNOWN> were not\n"
        "   in the database — fill them from the datasheet/TRM before building. */\n"
        "MEMORY\n{\n"
        f"  FLASH (rx)  : ORIGIN = {fb}, LENGTH = {fl}\n"
        f"  RAM   (rwx) : ORIGIN = {rb}, LENGTH = {rl}\n"
        "}\n\n"
        "/* Minimal sections skeleton — extend for your startup/vector table. */\n"
        "SECTIONS\n{\n"
        "  .text   : { *(.isr_vector) *(.text*) *(.rodata*) } > FLASH\n"
        "  .data   : { *(.data*) } > RAM AT > FLASH\n"
        "  .bss    : { *(.bss*) *(COMMON) } > RAM\n"
        "}\n")


def render_main_c(data: dict) -> str:
    return (
        "/* Auto-generated by EAEDK — minimal bare-metal entry stub. */\n"
        "int main(void)\n{\n"
        "    /* TODO: clock init, then your application. */\n"
        "    for (;;) { }\n"
        "    return 0;\n}\n")


# --- 3) flash instructions -------------------------------------------------

def render_flash(data: dict) -> str:
    b = data["board"] or {}
    name = data["project"]["name"]
    flash_base = _hex(b.get("flash_base")) or "<UNKNOWN flash_base>"
    flash_req = data["flash_req"]
    tool = flash_req["name"] if flash_req else None
    L = [f"# Flashing — {name}", ""]
    L.append(_draft_banner(data).rstrip("\n"))
    L.append(f"- **Board:** {data['board_name'] or '-'}")
    L.append(f"- **Flash base:** {flash_base}")
    L.append(f"- **Boot modes:** {b.get('boot_modes_json') or '<unknown>'}")
    L.append(f"- **Flash tool (from board profile):** {tool or '<not specified>'}")
    L.append("")
    L.append("## Command")
    profile = data.get("flash_profile")
    # Fix 2 (v1.7.0): for an OpenOCD board with a seeded SoC profile, fill in the real probe +
    # target cfg (e.g. Blue Pill + ST-Link) instead of <probe>/<target> placeholders.
    if tool == "openocd" and profile and profile.get("interface_cfg"):
        iface, target = profile["interface_cfg"], profile["openocd_target"]
        probe = profile.get("default_probe") or "your probe"
        openocd_cmds = [
            f"# Assumes a {probe} adapter (the most common for this board). "
            "Change the interface line if yours differs.",
            f'openocd -f {iface} -f {target} \\',
            f'        -c "program build/{name}.elf verify reset exit"']
    elif tool == "openocd":
        openocd_cmds = [
            "# Placeholders <probe>/<target> depend on your debug adapter and SoC config:",
            f'openocd -f interface/<probe>.cfg -f target/<target>.cfg \\',
            f'        -c "program build/{name}.elf verify reset exit"']
    else:
        openocd_cmds = None
    cmds = openocd_cmds if openocd_cmds is not None else {
        "st-flash": [f"st-flash write build/{name}.bin {flash_base}"],
        "dfu-util": [f"dfu-util -a 0 -s {flash_base}:leave -D build/{name}.bin"],
        "esptool.py": [f"esptool.py --chip esp32 write_flash {flash_base} build/{name}.bin"],
        "esptool": [f"esptool --chip esp32 write_flash {flash_base} build/{name}.bin"],
        "picotool": [f"picotool load build/{name}.uf2 && picotool reboot"],
    }.get(tool or "", [
        "# No flash tool in this board's profile. Typical options:",
        "#   openocd / st-flash / dfu-util / esptool.py / picotool — pick per your probe."])
    L.append("```bash")
    L.extend(cmds)
    L.append("```")
    # Other probes a beginner might have, from the seeded map — so a different adapter isn't a wall.
    if tool == "openocd" and profile and data.get("probes"):
        L.append("")
        L.append("Using a different probe? Swap the `interface/…cfg` for yours:")
        for p in data["probes"]:
            L.append(f"- **{p['name']}** → `{p['interface_cfg']}`"
                     + (f" — {p['summary']}" if p.get("summary") else ""))
    if data["detected_flash"] is None and tool:
        L.append("")
        L.append(f"> ⚠ `{tool}` was not detected on this host. Run `eaedk toolchain detect`; "
                 f"if missing, install it before flashing.")
    L.append("")
    return "\n".join(L) + "\n"
