"""Wokwi simulation files (v2.1.0) — board-aware diagram + config for the online simulator.

Wokwi has native parts only for specific boards; the map below is its catalogue (like the
debug-probe map). The board PART is chosen from the project's SoC/board data (read from SQLite),
not assumed; the firmware artifact extension follows the architecture. Unsupported boards get a
clear note instead of a broken/empty diagram. Pure: takes already-gathered data, returns files.
"""
from __future__ import annotations

import json

# board name -> Wokwi native part. These five are what Wokwi simulates natively.
WOKWI_BOARDS = {
    "STM32F103-BluePill": "board-blue-pill",
    "Raspberry-Pi-Pico": "board-pi-pico",
    "ESP32-DevKitC": "board-esp32-devkit-c",
    "Arduino-Uno": "board-arduino-uno",
    "Arduino-Mega": "board-arduino-mega",
}


def supported_boards() -> list[str]:
    return list(WOKWI_BOARDS)


def _firmware_name(project: str, arch: str | None) -> str:
    """The compiled artifact Wokwi loads — .hex for AVR, .uf2 for RP2040, .elf otherwise."""
    a = (arch or "").lower()
    if a == "avr":
        return f"build/{project}.hex"
    if "cortex-m0plus" in a:        # RP2040 firmware is a UF2
        return f"build/{project}.uf2"
    return f"build/{project}.elf"


def wokwi_files(board_name: str, soc: dict | None, project: str) -> dict[str, str]:
    """Return {relpath: content} for the wokwi/ folder. For an unsupported board this is a single
    README.txt explaining that and listing the supported boards — never a silent gap."""
    part = WOKWI_BOARDS.get(board_name)
    if part is None:
        names = ", ".join(supported_boards())
        return {"wokwi/README.txt":
                f"Wokwi simulation is not available for {board_name}.\n\n"
                f"Wokwi natively simulates these boards: {names}.\n"
                "If you have one of those, create a project for it to get simulation files.\n"}

    arch = (soc or {}).get("arch")
    diagram = {
        "version": 1,
        "author": "EAEDK",
        "editor": "wokwi",
        "parts": [
            {"type": part, "id": "dev", "top": 0, "left": 0, "attrs": {}},
        ],
        # The on-board LED on these boards is what the blink firmware drives, so a minimal
        # board-only diagram simulates the first project. No invented external wiring.
        "connections": [],
        "_eaedk": {"board": board_name, "soc": (soc or {}).get("name"), "arch": arch},
    }
    firmware = _firmware_name(project, arch)
    toml = (
        "# Wokwi config — generated by EAEDK. Points the simulator at your compiled firmware.\n"
        "[wokwi]\n"
        "version = 1\n"
        f"firmware = '{firmware}'\n"
        f"elf = 'build/{project}.elf'\n")
    return {"wokwi/diagram.json": json.dumps(diagram, indent=2) + "\n",
            "wokwi/wokwi.toml": toml}
